export default {
  DOWNLOAD_CONTEST_FILE_ACTION: 'DOWNLOAD_CONTEST_FILE_ACTION',
  DOWNLOAD_CONTEST_FILE_REQUEST: 'DOWNLOAD_CONTEST_FILE_REQUEST',
  DOWNLOAD_CONTEST_FILE_SUCCESS: 'DOWNLOAD_CONTEST_FILE_SUCCESS',
  DOWNLOAD_CONTEST_FILE_ERROR: 'DOWNLOAD_CONTEST_FILE_ERROR',
};
